name: newtons_cradle_loading_indicator
description: A loading indicator widget that resembles Newton's cradle , it consists of two swing balls and two fixed balls
version: 0.0.5
homepage: https://github.com/mohammedseifaldin/newtons-loading-indicator.git

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.20.0"
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/hit_sound.mp3
#  plugin:
#    platforms:
#      android:
#        package: come.example.newton
#        pluginClass: SaifPackage
#      ios:
#        pluginClass: SaifPackage
#      linux:
#        pluginClass: SaifPackage
#      macos:
#        pluginClass: SaifPackage
#      web:
#        pluginClass: SaifPackage
#        fileName: newtons_cradle_loading_indicator.dart
#      windows:
#        pluginClass: SaifPackage

screenshots:
  - description: 'Screenshot of the widget'
    path: 'assets/screenshot.png'

topics:
  - loading
  - animation
  - education
  - widgets
